### ISSUE TITLE
Microphone not running on Win10PXE Help me! ChrisRfr

### ISSUE THREAD

**Issue by WinPE10KTV** [ChrisRfr/Win10XPE#1]
The sound in my windows pe 10 works fine, but the microphone does not work, can someone help me fix this error, the file folder containing it, or the code to activate the microphone ?, BUILDER ON WINPXE 10 BY WINBUILDER thank you in advance. :)

**Comment by ChrisRfr** [comment]
You've already asked the same question on theoven forum, it's better there
