### ISSUE TITLE
Win10XPE

### ISSUE THREAD

**Issue by DaviRodrigues46** [ChrisRfr/Win10XPE#11]
Hi I'm trying to make the money work on my Samsung NP350xaa notebook and it doesn't work via USB when I try to install Windows 11 for lack of device driver I've tried everything and it doesn't work and the desktop icons are black

**Comment by ChrisRfr** [comment]
I don't see the link with Win10XPE! and you are not in a support center here!

**Comment by DaviRodrigues46** [comment]
hello chris i'm sorry for intruding but i'm a layman on win10xpe and
i'm having a problem installing win11 through the installer, it's
giving device driver error and won't install on the desktop the
default icons turn black don't appear right i'm sorry for fact ne not
get

**Comment by DaviRodrigues46** [comment]
hello chris i'm sorry for intruding but i'm a layman on win10xpe and
i'm having a problem installing win11 through the installer, it's
giving device driver error and won't install on the desktop the
default icons turn black don't appear right i'm sorry for fact ne not
get


Em sáb., 27 de nov. de 2021 10:59, ChrisR ***@***.***>
escreveu:

**Comment by PCAssistSoftware** [comment]
If you want support then try asking on the relevant forum - https://theoven.org/viewforum.php?f=14

**Comment by DaviRodrigues46** [comment]
I can't register on the forum already try all the questions to
register but it only gives an error


Em sáb., 27 de nov. de 2021 11:49, Darren Rose ***@***.***>
escreveu:

**Comment by PCAssistSoftware** [comment]
Forum is working perfectly fine for me - make sure answering security question correctly - answers are

![image](https://user-images.githubusercontent.com/10872799/143690047-83e08259-e5d4-4f4c-b9f0-457a315b0eec.png)

**Comment by PCAssistSoftware** [comment]
You could also try the "other" forum - http://reboot.pro/index.php?showforum=22

**Comment by DaviRodrigues46** [comment]
Thanks

Em sáb., 27 de nov. de 2021 13:54, Darren Rose ***@***.***>
escreveu:
