### ISSUE TITLE
Win10XPE and install.wim file not found but install.esd is there in 20H2

### ISSUE THREAD

**Issue by wmchin2003** [ChrisRfr/Win10XPE#16]
Hello,

I'm trying to make a WinPE media but I've noticed that the newer Windows 10 (20H2) iso files have install.esd on there.  I cannot find install.wim inside the sources folder.  Is there a workaround for this?

William

**Comment by PCAssistSoftware** [comment]
As per the instructions in WinBuiilder try downloading the ISO from correct source and then it should have WIM rather than ESD file

https://tb.rg-adguard.net/public.php

![image](https://user-images.githubusercontent.com/10872799/152767831-2cb862a7-884d-4381-9c51-90cca2361c0e.png)
