### ISSUE TITLE
Add Winrar integration as alternative to 7z

### ISSUE THREAD

**Issue by DCaedus** [ChrisRfr/Win10XPE#18]
Add Winrar integration as alternative to 7z

**Comment by ChrisRfr** [comment]
The project comes only with an application selection.
I don't try to support a large collection of applications on my side or make more support here.

You can use Utilities/Mega Optional Application Download, to download other apps script writen by KYHI, APT, ...
Or you can ask here [Win10XPE - Build Your Own Rescue Media [2]](https://www.tenforums.com/software-apps/182581-win10xpe-build-your-own-rescue-media-2-a.html) for help on adding other applications.
