### ISSUE TITLE
Triggers Multiple antivirus warnings on virustotal

### ISSUE THREAD

**Issue by Dr-Ari-Gami** [ChrisRfr/Win10XPE#2]
Here is a link to a virustotal scan for Win10XPE: https://www.virustotal.com/gui/file/243791cdc98ea98cbfab57449794fd9f55327eb8f6d5288d038c4300308e4c8c/detection

It upsets 8 antivirus softwares, any idea why? I'd like to be able to confirm that these are false positives before using this.

**Comment by ZingBlue** [comment]
This is very concerning why is this?

**Comment by ChrisRfr** [comment]
I added a note on the [Main Page](https://github.com/ChrisRfr/Win10XPE) (in ReadME.me)
False positive, I can't fight against Antivirus companies
