### ISSUE TITLE
Add Dark Reader Chrome extension please?

### ISSUE THREAD

**Issue by DCaedus** [ChrisRfr/Win10XPE#20]
Add Dark Reader Chrome extension please?

https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

Also ty for all your hard work love your software.

**Comment by ChrisRfr** [comment]
Same answer as here [Add Winrar integration as alternative to 7z](https://github.com/ChrisRfr/Win10XPE/issues/18#issuecomment-1048711057)
