### ISSUE TITLE
NSudo does not work with Windows 11 as source.

### ISSUE THREAD

**Issue by ggbbrr** [ChrisRfr/Win10XPE#23]
NSudo works OK with Win10.

But with **Win11**, it does not. NSudo error is "Error: Failed to create a process.".

Similarly Advanced Run (nirsoft) fails "The SecLogon service does not exist".

And, PowerRun (Sordum) "The specified service does not exist"

**Comment by 6100m** [comment]
(i'm not a maintainer of Win10XPE, but I wanna help anyway) :)
Referencing https://www.winhelponline.com/blog/windows-11-default-services-configuration/ as I am skipping Windows 11, the service should exist, but is set to manual. Try adding the following registry key into your PE source:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\seclogon]
"Start"=dword:00000000
```
and then reboot :)
If it still errors, seclogon.exe might be missing, so also try readding seclogon.exe into %windir%\system32\ and try adding that registry key again, and reboot once more :)

**Comment by ggbbrr** [comment]
Looks like the problem is not in Win10XPE or the NSudo script.

Some versions of NSudo work ok (at least they don't crash when run, lol). 
v8.0 and v6.2 work ok.
v8.2 does not.
