### ISSUE TITLE
How do I just extract the 001, 002 and 003 files?

### ISSUE THREAD

**Issue by C-H-O-N-G** [ChrisRfr/Win10XPE#30]
Hello there! I would like to ask how do I extract the 001, 002 and 003 files because I had an error while extracting. I followed the tutorials but it doesn't works for me -_-. 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/63568223/181785806-50e4d1d9-f02b-463a-bd10-7f80c4548fdc.png">

Thanks!

**Comment by RadegasTCZ** [comment]
I tried 7-zip and had no problems.

**Comment by C-H-O-N-G** [comment]
I still cant extract the 7z file in the 001 zip file. 

![image](https://user-images.githubusercontent.com/63568223/181909101-247f28df-b74a-42a8-a641-c3ddfc2b72a0.png)

can you send me the download link for the extracted files? It is hard to extract idk why even I use 7z

**Comment by PCAssistSoftware** [comment]
Try downloading the file again as it extracts fine for me too (also using 7-zip), so I suspect your download is corrupt

**Comment by C-H-O-N-G** [comment]
I already download many times

**Comment by C-H-O-N-G** [comment]
and 

> Try downloading the file again as it extracts fine for me too (also using 7-zip), so I suspect your download is corrupt

and also im using for 7z just now

**Comment by C-H-O-N-G** [comment]
oh now it can be extrated since I select all files and extract by 7z

**Comment by C-H-O-N-G** [comment]
but anyways thanks for helping me!

**Comment by RadegasTCZ** [comment]
Here's how to do it, may be also good idea to turn off defender while extracting. But I didn't observe any errors while extracting with Defender enabled.

https://user-images.githubusercontent.com/22341950/181910257-adb920e3-4d68-4443-9c84-c1d8d03a8ea9.mp4

.

**Comment by C-H-O-N-G** [comment]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/63568223/181911790-5bf7394a-572c-4fb8-9576-d98e09a08f8f.png">

it still can be extracted by winrar but idk why if I only download one of 001, 002 or 003 files, it cant be extracted so I tried to download all and it successed

**Comment by PCAssistSoftware** [comment]
I'm not sure why this is so difficult, download the zip file, extract the zip file, right click on the 001 file and extract it using 7-zip and 7-zip will automatically extract contents of all three spanned files (001. 002, 003) - exactly as per the instructions on the forum

**Comment by C-H-O-N-G** [comment]
actually extract 001 file then it is done

**Comment by RadegasTCZ** [comment]
> I'm not sure why this is so difficult, download the zip file, extract the zip file, right click on the 001 file and extract it using 7-zip and 7-zip will automatically extract contents of all three spanned files (001. 002, 003) - exactly as per the instructions on the forum

Exactly what I showed.
