### ISSUE TITLE
PENetwork Issue

### ISSUE THREAD

**Issue by C-H-O-N-G** [ChrisRfr/Win10XPE#31]
Hello there again! I have an issue about the PENetwork with this picture:
![image](https://user-images.githubusercontent.com/63568223/182013814-3b810c06-cea6-44ca-a40f-6cfb82b08ce5.png)

And I rebuilded for many times but I still can't connect to my network so I would like to ask how to solve this problem?

**Comment by PCAssistSoftware** [comment]
Looks like you haven't installed your wireless network drivers?

**Comment by C-H-O-N-G** [comment]
install it in PE?

**Comment by PCAssistSoftware** [comment]
Yes as part of building your PE

See image below - if you are booting your PE on the same computer you are building on then try checking the box "add host new drivers", if using it on other computers then add the wireless drivers for those machines by clicking "copy drivers here" and putting them in folder so they get included in build.

Suggest you start reading some of the documentation and posts on the forums as a lot of this is covered

![image](https://user-images.githubusercontent.com/10872799/182026924-1c3afc51-2887-45e4-adc3-4dd8b437dc4e.png)

**Comment by C-H-O-N-G** [comment]
But if I used it on many machines, I needed to install all?

**Comment by PCAssistSoftware** [comment]
Depends, I use it on a lot of machines and if picks up most ethernet as standard drivers built into Windows 10 ISO, for wireless it picks up some but not all.  For my use I carry a USB wireless dongle and just integrate drivers for that so I can plug that in and always have wireless working on any machine without having to integrate loads of drivers.

**Comment by C-H-O-N-G** [comment]
oh ok then...I will try now and imma gonna to close this issue since it have a step to solve it.

**Comment by C-H-O-N-G** [comment]
but wait it still the same screen in the penetwork even though I check the box of "adding host net drivers".

**Comment by C-H-O-N-G** [comment]
before this, I can connect the network but now cant

**Comment by PCAssistSoftware** [comment]
Try doing some simple basic troubleshooting yourself e.g. look in device manager and see if wireless adapter installed and showing etc.   And as previous reply try going to forum and asking question as github is not really the place to get support for using Win10XPE

**Comment by C-H-O-N-G** [comment]
for the driver, I got installed since intel driver support assistant will update itself. With the forum, I will ask there and close this issue.
