### ISSUE TITLE
"Cannot open file as archive" while trying to extract the other two .7z files on 2022-01-07

### ISSUE THREAD

**Issue by ValkTheBoxman** [ChrisRfr/Win10XPE#33]
i'm having the problem thats in the title.

**Comment by PCAssistSoftware** [comment]
Look at issue 30 and see if that helps

https://github.com/ChrisRfr/Win10XPE/issues/30

**Comment by ValkTheBoxman** [comment]
> Look at issue 30 and see if that helps
> 
> https://github.com/ChrisRfr/Win10XPE/issues/30

I am using 7zip, probably my file is corrupted.

**Comment by PCAssistSoftware** [comment]
Try downloading it again then, because as per replies on that closed issue the files extract perfectly fine if you follow the instructions provided

**Comment by ValkTheBoxman** [comment]
Well i did try extracting all of them at once, but the only file that got extracted was the 01 file

**Comment by ValkTheBoxman** [comment]
Problem fixed. Now i have a great addition to my Ventoy Multiboot rescue USB.

**Comment by ValkTheBoxman** [comment]
I forgot to close it since i have done it! It works perfectly with Ventoy USB
