### ISSUE TITLE
DirMove - Failed to move directory

### ISSUE THREAD

**Issue by banhsmif** [ChrisRfr/Win10XPE#4]
I just follow your tutorial but i have some trouble and i don't know how to solve this, so could you help me fix that ??
DirMove - Failed to move directory [%BaseDir%\Projects\Tools\ADK_6\amd64\BCDBoot] to: [%BaseDir%\Projects\Tools\x64]: Unknown error

**Comment by ChrisRfr** [comment]
This is fixed in the new version 2020-10-29
Microsoft has recently removed some old links and the download of the ADK tools was not complete, thus the bug
GetWaikTool (GWT) has been updated and fixes the error.

**Comment by sauluspaulus** [comment]
Hi, I have the same problem as banhsmif,
with version Win10XPE_2021-01-16
is there an option to download and place the files manually?

DirMove - Failed to move directory [%BaseDir%\Projects\Tools\ADK_6\amd64\BCDBoot] to: [%BaseDir%\Projects\Tools\x64]: Unknown error
