### ISSUE TITLE
creating ISO file

### ISSUE THREAD

**Issue by bhong2002** [ChrisRfr/Win10XPE#59]
an error whene creating iso file

![image](https://github.com/ChrisRfr/Win10XPE/assets/15363312/3376ec9e-c995-4f3a-9d52-23d72434445a)

**Comment by bhong2002** [comment]
Solved with disabling windows defender real time protection... but where can i find the *.iso file? . . .

**Comment by PCAssistSoftware** [comment]
Usually in the same located you are running winbuilder (Win10XPE.exe) from.

Recommend you add an exception to windows defender for your build folder then you wouldn't need to disable it

**Comment by bhong2002** [comment]
here the warning log...

![image](https://github.com/ChrisRfr/Win10XPE/assets/15363312/b4e0235d-b7b7-4aaf-87c2-104fe808e034)

**Comment by PCAssistSoftware** [comment]
Click on create iso down the left hand side and then click the button labelled "create iso" and see if it now creates it

**Comment by bhong2002** [comment]
Still none *.ISO file on base folder . . . 

![image](https://github.com/ChrisRfr/Win10XPE/assets/15363312/63519e37-d877-4223-8626-ff721c831a2a)
![image](https://github.com/ChrisRfr/Win10XPE/assets/15363312/5fce94d9-27b7-4d15-9baa-3081a8b5b5d4)

**Comment by bhong2002** [comment]
SOLVED.... i forgot to uncheck this  ... 😄 ..... sorry ....

![image](https://github.com/ChrisRfr/Win10XPE/assets/15363312/a2a5653f-222a-4c5e-ad71-0637887d14b2)
