### ISSUE TITLE
 DirCopy - Failed to copy directory [%BaseDir%\Temp\Produkey_x64\Produkey_x64] to: [%BaseDir%\ISO\Programs]: Unknown error [Warning]

### ISSUE THREAD

**Issue by yukun314** [ChrisRfr/Win10XPE#6]
File [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE.Script] Version[3]    Processing ProduKey...  IF - File exists: [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE_File.Script] evaluated string: [If,Not,ExistFile,%FileContainer%,Exit,"%FileContainer% Container File Not Found"]  IF - [run from usb] is not equal to: [run from ram] evaluated string: [If,%RunFromWhere_ScrollBox%,Equal,"Run From RAM",RunFromRAM]  IF - [x64] is equal to: [x64] evaluated string: [If,%Architecture%,Equal,x64,Run,%ScriptFile%,PluginSetx64]
--
Run - Processing section: [PluginSetx64] From file: [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE.Script]        SetVar - Sucessfuly changed the value of [%ProgramFolder%] to: [Produkey_x64]        SetVar - Sucessfuly changed the value of [%SetupFile%] to: [produkey-x64.zip]        SetVar - Sucessfuly changed the value of [%SetupURL%] to: [%SetupURLx64%] Run - Processed section [PluginSetx64] in file: [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE.Script]
[//--]
Run - Processing section: [Extract] From file: [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE.Script]        SetVar - Sucessfuly changed the value of [%SetupContainerSize%] to: []        IniRead - [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE_File.Script] Section [Folder] Key [produkey-x64.zip] to variable: [%SetupContainerSize%] with value [81075,108100]        IF - [81075,108100-] is not equal to: [-] evaluated string: [If,%SetupContainerSize%-,Equal,-,Run,%ScriptFile%,Update_Container]        [//--]        Extracting ProduKey Setup File...        IF - Directory does not exist: [%BaseDir%\Temp\Produkey_x64] evaluated string: [If,ExistDir,%GTemp%\%ProgramFolder%,DirDeleteQ,%GTemp%\%ProgramFolder%]        DirMake - Created directory: [%BaseDir%\Temp\Produkey_x64]        ExtractFile - [produkey-x64.zip] to: [%BaseDir%\Temp\Produkey_x64]        ShellExecute: [Hide] using: [%BaseDir%\Projects\Tools\7z.exe] with parameters: [x "%BaseDir%\Temp\Produkey_x64\produkey-x64.zip" -y -o"%BaseDir%\Temp\Produkey_x64\Produkey_x64"] Run - Processed section [Extract] in file: [%BaseDir%\Projects\MyPlugins\Apps\Security\produkey_XPE.Script]
[//--]  IF - Directory does not exist: [%BaseDir%\ISO\Programs\Produkey_x64] evaluated string: [If,ExistDir,%Target_Prog%\%ProgramFolder%,DirDeleteQ,%Target_Prog%\%ProgramFolder%]  IF - Directory exists: [%BaseDir%\ISO\Programs] evaluated string: [If,Not,ExistDir,%Target_Prog%,DirMake,%Target_Prog%] DirCopy - Failed to copy directory [%BaseDir%\Temp\Produkey_x64\Produkey_x64] to: [%BaseDir%\ISO\Programs]: Unknown error Halt  Script time: 703 milliseconds  Finished processing script: ProduKey      Project time: 4 minutes, 45 seconds and 21 milliseconds  OnBuildExit [Exec,%ProjectDir%\script.project,WinXPE_OnBuildExit,ERROR]
Exec - Processing section: [WinXPE_OnBuildExit] From file: [%BaseDir%\Projects\Win10XPE\script.project]        with parameters: [ERROR]        AddVariables - Added section [ApiVar] from file [%BaseDir%\Projects\Win10XPE\Macro.script] into the local variable list        IF - Directory exists: [%BaseDir%\Target] evaluated string: [If,ExistDir,%GTarget%,Run,%ScriptFile%,HiveUnload,%GTarget%]
Run - Processing section: [HiveUnload] From file: [%BaseDir%\Projects\Win10XPE\script.project]              with parameters: [%BaseDir%\Target]                    IF - [%BaseDir%\target-] is not equal to: [-] evaluated string: [If,Not,#1-,Equal,-,Begin]                    ShellExecute: [Hide] using: [%BaseDir%\Projects\Tools\HiveUnload.exe] with parameters: [ /HKLM /Target:"%BaseDir%\Target"]                          IF - [2] is not equal to: [1] evaluated string: [If,%ExitCode%,Equal,1,Begin]                          [EchoExtended,"Error on Unloading hives from#$x#$x%1\Windows\System32\config#$x#$xCommon Reason: Loaded Hives is being used by ex: regedit.exe#$xClose the program which locks the hives.",Warn,,MessageError,10]                    [End]              [End]       Run - Processed section [HiveUnload] in file: [%BaseDir%\Projects\Win10XPE\script.project]        IF - Directory exists: [%BaseDir%\Temp] evaluated string: [If,ExistDir,%GTemp%,Run,%ScriptFile%,HiveUnload,%GTemp%]
Run - Processing section: [HiveUnload] From file: [%BaseDir%\Projects\Win10XPE\script.project]              with parameters: [%BaseDir%\Temp]                    IF - [%BaseDir%\temp-] is not equal to: [-] evaluated string: [If,Not,#1-,Equal,-,Begin]                    ShellExecute: [Hide] using: [%BaseDir%\Projects\Tools\HiveUnload.exe] with parameters: [ /HKLM /Target:"%BaseDir%\Temp"]                          IF - [2] is not equal to: [1] evaluated string: [If,%ExitCode%,Equal,1,Begin]                          [EchoExtended,"Error on Unloading hives from#$x#$x%1\Windows\System32\config#$x#$xCommon Reason: Loaded Hives is being used by ex: regedit.exe#$xClose the program which locks the hives.",Warn,,MessageError,10]                    [End]              [End]       Run - Processed section [HiveUnload] in file: [%BaseDir%\Projects\Win10XPE\script.project]              IF - [error] is equal to: [error] evaluated string: [If,#1,Equal,ERROR,Begin]             Build Stopped due to an Error.        [End]              IF - [error] is not equal to: [exception] evaluated string: [If,#1,Equal,EXCEPTION,Begin]              [Echo,"Build Stopped by Exception.",Warn]        [End]              IF - [error] is not equal to: [stop] evaluated string: [If,#1,Equal,STOP,Begin]              [Echo,"Build Stopped by User.",Warn]        [End]              IF - [error] is not equal to: [command] evaluated string: [If,#1,Equal,COMMAND,Begin]              [Echo,"Build Stopped by script Command.",Warn]        [End]        IF - [error] is not equal to: [done] evaluated string: [If,#1,Equal,DONE,Message,"Success of the Project Building. Enjoy :)",Information,2]        [//-]              IF - [true] is equal to: [true] evaluated string: [If,%SupportLog_CheckBox%,Equal,True,Begin]              IF - File exists: [%BaseDir%\Projects\Win10XPE\Features\SupportLog_XPE.script] evaluated string: [If,ExistFile,%ProjectDir%\Features\SupportLog_XPE.script,Exec,%ProjectDir%\Features\SupportLog_XPE.script,Process]
Exec - Processing section: [Process] From file: [%BaseDir%\Projects\Win10XPE\Features\SupportLog_XPE.script]                    AddVariables - Added section [ApiVar] from file [%BaseDir%\Projects\Win10XPE\Macro.script] into the local variable list                    Processing SupportLog...                    StrFormat - converted [DATE(%CurrentDateYYMD%,yyyymmdd)] to variable: [%CurrentDateYYMD%] with result: [20210103]                    StrFormat - converted [DATE(%CurrentDateHN%,hhnn)] to variable: [%CurrentDateHN%] with result: [1153]                    ShellExecute: [Hide] using: [cmd.exe] with parameters: [/D /C Exit %TIME:~6,2%]                    SetVar - Sucessfuly changed the value of [%CurrentDateS%] to: [32]                    SetVar - Sucessfuly changed the value of [%CurrentDate%] to: [20210103_115332]                    [//-]                    IF - Directory does not exist: [%BaseDir%\Temp\SupportLog] evaluated string: [If,ExistDir,%GTemp%\%ProgramFolder%,DirDeleteQ,%GTemp%\%ProgramFolder%]                    DirMake - Created directory: [%BaseDir%\Temp\SupportLog]                    System - Refreshing interface after finishing processing

**Comment by ChrisRfr** [comment]
Adds an AntiVirus exception on the base folder.
[NirSoft's ProduKey](https://www.nirsoft.net/utils/product_cd_key_viewer.html) is marked as positive by some AV. It is a **False Alarm**

**Comment by CodeDiseaseDev** [comment]
anti virus is disabled for me
im frustrated that i just wasted 30 minutes
