### ISSUE TITLE
(False positive) Infected with Trojan

### ISSUE THREAD

**Issue by howarddo2208** [ChrisRfr/Win10XPE#64]
![image](https://github.com/ChrisRfr/Win10XPE/assets/62332195/846a1613-f9ba-4297-8130-ce32cc3a1f2e)
https://www.pcrisk.com/removal-guides/14739-win32-skeeyah-trojan
What's this? I don't think this is a false alarm.

**Comment by ChrisRfr** [comment]
It's a False Alarm
You can send them this file for full analysis. Is pcrisk.com reliable ? um, not sure !
And you can add an exception on Win10XPE folder, GWT.exe is safe or don't use Win10XPE at all. More than 400,000 downloads and over 500 stars, it's up to you!

Please read this, at the bottom of the Win10XPE presentation (Readme.md), as well as the linked blog from nirsoft, a well-known developer:
> **Note AV**: By its nature, **Win10XPE** uses programs or applications which uses functions at the core of windows.
> Some AntiVirus mark them as positive. These are false alarms.
> An example with NirSoft's ProduKey to Recover lost Windows product key, 12 engines detected this file as Unsafe or Hacktool, that's not true.
> You can read this blog written by the same author as ProduKey: [Antivirus companies cause a big headache to small developers](https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/).
> Blog written in 2009, the situation did not get any better.
> It shouldn't be like that and it's really frustrating. The work of AV companies should be better.
> They should be reprimanded for this, we are their customers.
> I can only advise you to put an exclusion on the Win10XPE folder.

Generally speaking, take the AV results with a degree of caution :smirk:
