### ISSUE TITLE
Nothing happens after clicking "Download Source ISO"

### ISSUE THREAD

**Issue by Windows10User2** [ChrisRfr/Win10XPE#67]
Nothing happens after clicking "Download Source ISO" except a command prompt window opening that supposedly starts downloading something and closes in a second. Where is the ISO image downloaded?

**Comment by ChrisRfr** [comment]
It should download Fido.ps1.lzma (from https://github.com/pbatard/Fido latest release) into the Temp\Fido folder, extract Fido.ps1 into the same folder and launch it with Powershell to open a new window:

![image](https://github.com/ChrisRfr/Win10XPE/assets/4269099/c009d1a8-94c6-4eae-8c03-06ee66ead4d0)

Is there a problem with Powershell on your machine?
Alternatively, you can download ISOs here:
https://files.rg-adguard.net/   (File list > Operating Systems > )
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-11-enterprise (change en-us to your language)
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise

**Comment by Windows10User2** [comment]
In my case it doesn't, and even if it did, I think it should be explained somewhere. Also, which Windows 11 ISOs does this program support and why is it called Win10XPE if it supports Windows 11? Will there be a program called Win11XPE?

**Comment by ChrisRfr** [comment]
You close the discussion without saying which windows 11 image ? which error ?

> I think it should be explained somewhere. Also, which Windows 11 ISOs does this program support
explained
Would you have read it if it was explained! The list of supported ISOs is written at the bottom of the [Win10XPE Github main page](https://github.com/ChrisRfr/Win10XPE#readme)

**Comment by Windows10User2** [comment]
> You close the discussion without saying which windows 11 image ? which error ? Same pirated version as [here](https://www.tenforums.com/bsod-crashes-debugging/146970-random-bsods-when-turning-my-pc.html) ?
> 
> > I think it should be explained somewhere. Also, which Windows 11 ISOs does this program support
> > explained
> 
> Would you have read it if it was explained! The list of supported ISOs is written at the bottom of the [Win10XPE Github main page](https://github.com/ChrisRfr/Win10XPE#readme)

Windows 11 22H2 22621.1702. I don't know.

That wasn't a pirate image.

I did read and it still didn't work, don't you think? What kind of english is that?
