### ISSUE TITLE
Error when creating image

### ISSUE THREAD

**Issue by RandomGuy2023** [ChrisRfr/Win10XPE#68]
When creating the ISO, on the Build Core [Core.script] part, a window opens stating:

"error, file not found.
C:\Windows\System32\Drivers\DriverStore\FileRepository\rt68cx21x64.inf_amd64_8db01a9992cf3fbb\rt68cx21x64.sys".

I can stil proceed by clicking "OK" and the image is created. I run Win10XPE in another PC and I have this issue as well. I used Win10XPE to download the Windows 11 22H2 22621.1702 build.

Also, Win10XPE ignores the directories I set on the "Path" tab.

**Comment by ChrisRfr** [comment]
rt68cx21x64.inf is not used, written anywhere in the project scripts. bye

**Comment by Thandibirani** [comment]
ha
